#!/bin/sh
# clear cached assets (unversioned/ignored files)
git clean -x -f -- public

# clean unversioned files from vendor (e.g. old submodules)
git clean -d -f -- vendor

# update composer
php composer.phar self-update

# install composer modules
if [ ! -f composer.lock ]; then
	php composer.phar install
else
	php composer.phar update
fi
